let protocolData = [];
let selectedProtocols = new Set();

// Load the JSON generated by generate_protocol_keywords.ts
async function loadData() {
    try {
        const response = await fetch('../scripts/protocol_rag_db.json');
        if (!response.ok) throw new Error("Failed to load local RAG DB");
        protocolData = await response.json();
        renderGrid(protocolData);
    } catch (e) {
        console.error("Error loading JSON:", e);
        document.getElementById('stats').innerText = "Failed to load database. Ensure the TS script was run.";
    }
}

function renderGrid(data) {
    const grid = document.getElementById('grid');
    grid.innerHTML = '';
    
    document.getElementById('stats').innerText = `Showing ${data.length} Proxy Pointer RAG Schemas`;

    data.forEach(item => {
        const card = document.createElement('div');
        card.className = `card ${selectedProtocols.has(item.protocol_name) ? 'selected' : ''}`;
        card.onclick = () => toggleSelection(item.protocol_name, card);

        const tagsHtml = item.category_tags.map(t => `<span class="tag">${t}</span>`).join('');
        const keywordsHtml = item.keywords.slice(0, 3).map(k => `<span class="tag keyword">#${k}</span>`).join('');

        card.innerHTML = `
            <div class="card-header">
                <h3 class="card-title">${item.protocol_name.replace('.md', '')}</h3>
            </div>
            <p class="card-desc">${item.description}</p>
            <div class="tags">
                ${tagsHtml}
                ${keywordsHtml}
            </div>
        `;
        
        grid.appendChild(card);
    });
}

function toggleSelection(name, cardEl) {
    if (selectedProtocols.has(name)) {
        selectedProtocols.delete(name);
        cardEl.classList.remove('selected');
    } else {
        selectedProtocols.add(name);
        cardEl.classList.add('selected');
    }
    updateSelectionPanel();
}

function updateSelectionPanel() {
    const panel = document.getElementById('selectionPanel');
    const count = document.getElementById('selectionCount');
    
    count.innerText = selectedProtocols.size;
    
    if (selectedProtocols.size > 0) {
        panel.classList.add('active');
    } else {
        panel.classList.remove('active');
    }
}

// Search functionality
document.getElementById('searchInput').addEventListener('input', (e) => {
    const term = e.target.value.toLowerCase();
    
    if (!term) {
        renderGrid(protocolData);
        return;
    }
    
    const filtered = protocolData.filter(item => {
        const searchString = [
            item.protocol_name,
            item.description,
            ...item.category_tags,
            ...item.keywords
        ].join(' ').toLowerCase();
        
        return searchString.includes(term);
    });
    
    renderGrid(filtered);
});

function exportSelection() {
    const selectedData = protocolData.filter(p => selectedProtocols.has(p.protocol_name));
    console.log("Exporting to Context7 / Session Memory:", selectedData);
    alert(`Successfully generated proxy pointer RAG bounds for ${selectedData.length} items.\n(Console contains JSON payload)`);
}

// Init
loadData();
